# Septuagint agent logic with backtranslation
# lxx.py

import openai
import os

# Set your OpenAI API key here or via environment variable
openai.api_key = os.getenv("OPENAI_API_KEY")

# STEP A — Greek LXX verse lookup (expandable)
LXX_GREEK = {
    "Isaiah 7:14": "διὰ τοῦτο δώσει κύριος αὐτὸς ὑμῖν σημεῖον· ἰδοὺ ἡ παρθένος ἐν γαστρὶ λήμψεται καὶ τέξεται υἱόν, καὶ καλέσεις τὸ ὄνομα αὐτοῦ Εμμανουηλ.",
    "Genesis 1:1": "ἐν ἀρχῇ ἐποίησεν ὁ Θεὸς τὸν οὐρανὸν καὶ τὴν γῆν.",
    "Psalm 22:16": "ὤρυξαν χεῖράς μου καὶ πόδας.",
}

# STEP B — Function to call GPT and get Hebrew retroversion + gloss
def get_lxx_retroversion(reference):
    greek = LXX_GREEK.get(reference)
    if not greek:
        return {
            "greek": "[Not available]",
            "hebrew": "[Not available]",
            "english": "[Not available]",
            "notes": f"LXX verse '{reference}' not found in local set."
        }

    prompt = f"""
You are a biblical linguist. The following is a verse from the Greek Septuagint:

Greek: {greek}

Please:
1. Reconstruct a plausible Biblical Hebrew retroversion.
2. Provide a literal, word-for-word English gloss under each Hebrew word.
3. Format the result cleanly.

Return only:
- Greek (original)
- Hebrew (reconstructed)
- English (word-for-word gloss)
"""

    try:
        response = openai.ChatCompletion.create(
            model="gpt-4",
            messages=[
                {"role": "user", "content": prompt}
            ],
            temperature=0.5,
            max_tokens=500
        )

        reply = response.choices[0].message.content.strip()

        return {
            "greek": greek,
            "hebrew_english_output": reply,
            "notes": "Retroversion generated by ChatGPT (GPT-4) from LXX Greek."
        }

    except Exception as e:
        return {
            "greek": greek,
            "hebrew_english_output": "[API Error]",
            "notes": str(e)
        }
