/**
 * Curated index of commonly cited Dead Sea Scroll biblical witnesses.
 * Tier 1 = core biblical witnesses used in source-text reconstruction.
 * Tier 2 = add later (sectarian / rewritten-Bible / parabiblical).
 * Category: 'biblical' | 'commentary' | 'parabiblical'
 */

export type DSSCategory = 'biblical' | 'commentary' | 'parabiblical';
export type DSSTier = 1 | 2;

export interface DSSWitness {
  id: string;           // primary siglum e.g. "1QIsaᵃ"
  altId?: string;       // numeric alias e.g. "4Q37"
  commonName: string;   // e.g. "Great Isaiah Scroll"
  book: string;         // biblical book(s) covered
  date: string;         // paleographic date
  source: string;       // DJD volume or publication
  description: string;  // why it matters
  category: DSSCategory;
  tier: DSSTier;
  torahBook?: string;   // if Torah: matches dss-dates.ts key (e.g. "Exod")
  iahUrl?: string;      // Leon Levy DSS Digital Library URL
  paleo?: boolean;      // paleo-Hebrew script
}

export const DSS_WITNESSES: DSSWitness[] = [

  // ── TIER 1 · BIBLICAL ──────────────────────────────────────────────────────

  {
    id: '1QIsaᵃ',
    commonName: 'Great Isaiah Scroll',
    book: 'Isaiah',
    date: 'c. 125 BCE',
    source: 'DJD I (Barthélemy & Milik, 1955)',
    description: 'The flagship biblical DSS manuscript — nearly complete Isaiah (all 66 chapters). The oldest surviving copy of any complete biblical book, ca. 125 BCE. Indispensable for Isaiah textual variants against the later Masoretic tradition.',
    category: 'biblical',
    tier: 1,
    iahUrl: 'https://www.deadseascrolls.org.il/explore-the-archive/manuscript/E1-1',
  },
  {
    id: '1QIsaᵇ',
    commonName: 'Isaiah Scroll b',
    book: 'Isaiah',
    date: 'c. 50–1 BCE',
    source: 'DJD I (Barthélemy & Milik, 1955)',
    description: 'More fragmentary than 1QIsaᵃ but often closer to the Masoretic text — valuable as a comparison witness that shows two distinct textual streams existed simultaneously at Qumran.',
    category: 'biblical',
    tier: 1,
  },
  {
    id: '4QpaleoExodᵐ',
    altId: '4Q22',
    commonName: 'Paleo-Exodus m',
    book: 'Exodus',
    date: 'c. 100–50 BCE',
    source: 'DJD IX (Skehan, Ulrich & Sanderson, 1992)',
    description: 'Major proto-Samaritan-style witness to Exodus in paleo-Hebrew script. Contains significant expansions harmonising Exodus with Deuteronomy, demonstrating that multiple Torah text-types circulated before the Masoretic standardisation.',
    category: 'biblical',
    tier: 1,
    torahBook: 'Exod',
    paleo: true,
    iahUrl: 'https://www.deadseascrolls.org.il/explore-the-archive/manuscript/4Q22-1',
  },
  {
    id: '4QExod-Levᶠ',
    altId: '4Q17',
    commonName: 'Exodus–Leviticus f',
    book: 'Exodus · Leviticus',
    date: 'c. 250–200 BCE',
    source: 'DJD XII (Ulrich, Cross et al., 1994)',
    description: 'One of the oldest Torah witnesses in the DSS corpus — spans Exodus and Leviticus and pushes textual evidence back to the late 3rd century BCE. Important for showing Torah transmission before the Hasmonean period.',
    category: 'biblical',
    tier: 1,
    torahBook: 'Exod',
    iahUrl: 'https://www.deadseascrolls.org.il/explore-the-archive/manuscript/4Q17-1',
  },
  {
    id: '4QLevᵇ',
    altId: '4Q24',
    commonName: 'Leviticus b',
    book: 'Leviticus',
    date: 'c. 50 BCE–1 CE',
    source: 'DJD XII (Ulrich, Cross et al., 1994)',
    description: 'Important Leviticus witness from Cave 4; Hasmonean parchment. Part of the group of Leviticus manuscripts that collectively provide substantial coverage of the book against the Masoretic Text.',
    category: 'biblical',
    tier: 1,
    torahBook: 'Lev',
    iahUrl: 'https://www.deadseascrolls.org.il/explore-the-archive/manuscript/4Q24-1',
  },
  {
    id: '11QpaleoLevᵃ',
    altId: '11Q1',
    commonName: 'Paleo-Leviticus a',
    book: 'Leviticus',
    date: 'c. 100–25 BCE',
    source: 'DJD XXIII (García Martínez, Tigchelaar & van der Woude, 1998)',
    description: 'Major paleo-Hebrew Leviticus witness from Cave 11. One of the longest surviving Torah scrolls from Qumran in paleo-Hebrew script; often cited for its close agreement with the proto-Masoretic tradition.',
    category: 'biblical',
    tier: 1,
    torahBook: 'Lev',
    paleo: true,
  },
  {
    id: '4QNumᵇ',
    altId: '4Q27',
    commonName: 'Numbers b',
    book: 'Numbers',
    date: 'c. 100–50 BCE',
    source: 'DJD XII (Ulrich, Cross et al., 1994)',
    description: 'The most extensive Numbers witness in the DSS corpus. Contains numerous small variants and proto-Samaritan-type harmonisations, making it a key witness for Numbers textual criticism and DSS–LXX agreements.',
    category: 'biblical',
    tier: 1,
    torahBook: 'Num',
  },
  {
    id: '4QDeutʲ',
    altId: '4Q37',
    commonName: 'Deuteronomy j',
    book: 'Deuteronomy',
    date: 'c. 100–50 BCE',
    source: 'DJD XIV (White Crawford et al., 1995)',
    description: 'Large and significant Deuteronomy witness preserving 76 fragments across 18 plates. Covers substantial portions of Deuteronomy and is frequently cited for text-critical comparisons with the Masoretic tradition.',
    category: 'biblical',
    tier: 1,
    torahBook: 'Deut',
    iahUrl: 'https://www.deadseascrolls.org.il/explore-the-archive/manuscript/4Q37-1',
  },
  {
    id: '4QDeutⁿ',
    altId: '4Q41',
    commonName: 'Deuteronomy n',
    book: 'Deuteronomy · Decalogue',
    date: 'c. 50–1 BCE',
    source: 'DJD XIV (White Crawford et al., 1995)',
    description: 'Preserves one of the earliest known manuscript copies of the Ten Commandments. Featured by the IAA as a highlighted DSS exhibit. Contains an expanded form of the Decalogue combining elements from both Exodus 20 and Deuteronomy 5.',
    category: 'biblical',
    tier: 1,
    torahBook: 'Deut',
    iahUrl: 'https://www.deadseascrolls.org.il/featured-scrolls/',
  },
  {
    id: '4QDeutᵖ',
    altId: '4Q43',
    commonName: 'Deuteronomy p',
    book: 'Deuteronomy',
    date: 'c. 50 BCE–1 CE',
    source: 'DJD XIV (White Crawford et al., 1995)',
    description: 'Hasmonean Deuteronomy witness useful alongside 4QDeutʲ and 4QDeutⁿ for tracing the textual history of Deuteronomy in the late Second Temple period.',
    category: 'biblical',
    tier: 1,
    torahBook: 'Deut',
    iahUrl: 'https://www.deadseascrolls.org.il/explore-the-archive/manuscript/4Q43-1',
  },
  {
    id: '4QSamᵃ',
    altId: '4Q51',
    commonName: 'Samuel a',
    book: '1–2 Samuel',
    date: 'c. 250–200 BCE',
    source: 'DJD XVII (Cross et al., 2005)',
    description: 'One of the most important DSS biblical manuscripts — 665 fragments spanning 1–2 Samuel. Frequently agrees with the Septuagint against the Masoretic Text and has substantially shaped modern Samuel text-critical scholarship.',
    category: 'biblical',
    tier: 1,
    iahUrl: 'https://www.deadseascrolls.org.il/explore-the-archive/manuscript/4Q51-2',
  },
  {
    id: '4QSamᵇ',
    altId: '4Q52',
    commonName: 'Samuel b',
    book: '1 Samuel',
    date: 'c. 250 BCE',
    source: 'DJD XVII (Cross et al., 2005)',
    description: 'Among the oldest Hebrew biblical manuscripts discovered — early Hellenistic period (c. 250 BCE). Useful alongside 4QSamᵃ for showing that distinct Samuel text-types were in circulation before the Maccabean period.',
    category: 'biblical',
    tier: 1,
    iahUrl: 'https://www.deadseascrolls.org.il/explore-the-archive/manuscript/4Q52-1',
  },
  {
    id: '4QSamᶜ',
    altId: '4Q53',
    commonName: 'Samuel c',
    book: '1–2 Samuel',
    date: 'c. 100–50 BCE',
    source: 'DJD XVII (Cross et al., 2005)',
    description: 'Hasmonean Samuel witness; completes the Cave 4 Samuel triad (4QSamᵃ, ᵇ, ᶜ) showing multiple Samuel text-types in concurrent circulation at Qumran.',
    category: 'biblical',
    tier: 1,
    iahUrl: 'https://www.deadseascrolls.org.il/explore-the-archive/manuscript/4Q53-1',
  },
  {
    id: '4QKgs',
    altId: '4Q54',
    commonName: 'Kings',
    book: '1 Kings',
    date: 'c. 50–1 BCE',
    source: 'DJD XIV (White Crawford et al., 1995)',
    description: 'One of the few DSS witnesses to the books of Kings — a sparsely represented corpus at Qumran. Important precisely because Kings is so rarely attested in the scrolls.',
    category: 'biblical',
    tier: 1,
  },
  {
    id: '4QJerᵇ',
    altId: '4Q71',
    commonName: 'Jeremiah b',
    book: 'Jeremiah',
    date: 'c. 200–150 BCE',
    source: 'DJD XV (Ulrich et al., 1997)',
    description: 'Crucially supports the shorter Jeremiah textual tradition reflected in the Septuagint — approximately one-seventh shorter than the Masoretic Jeremiah. Demonstrates that both a shorter and a longer Jeremiah existed as independent Hebrew texts in the Second Temple period.',
    category: 'biblical',
    tier: 1,
  },
  {
    id: '4QJerᵈ',
    altId: '4Q72a',
    commonName: 'Jeremiah d',
    book: 'Jeremiah',
    date: 'c. 50–1 BCE',
    source: 'DJD XV (Ulrich et al., 1997)',
    description: 'Additional DSS Jeremiah witness supporting the shorter textual tradition; alongside 4QJerᵇ it confirms that the two-text Jeremiah situation was not an accident of translation but reflects two genuine Hebrew Vorlagen.',
    category: 'biblical',
    tier: 1,
  },
  {
    id: '4QEzekᵃ',
    altId: '4Q73',
    commonName: 'Ezekiel a',
    book: 'Ezekiel',
    date: 'c. 50 BCE–1 CE',
    source: 'DJD XV (Ulrich et al., 1997)',
    description: 'Key Ezekiel witness. The DSS Ezekiel fragments are relatively sparse but important for confirming textual stability in a book with complex versional history.',
    category: 'biblical',
    tier: 1,
  },
  {
    id: '4QDanᵃ',
    altId: '4Q112',
    commonName: 'Daniel a',
    book: 'Daniel',
    date: 'c. 125–100 BCE',
    source: 'DJD XVI (Ulrich et al., 2000)',
    description: 'Important for dating and textual transmission debates around Daniel. Daniel is among the better-represented books at Qumran (8 copies) and 4QDanᵃ is the primary witness, containing both Hebrew and Aramaic portions of the book.',
    category: 'biblical',
    tier: 1,
  },
  {
    id: '4QDanᵇ',
    altId: '4Q113',
    commonName: 'Daniel b',
    book: 'Daniel',
    date: 'c. 20–50 CE',
    source: 'DJD XVI (Ulrich et al., 2000)',
    description: 'Additional Daniel witness from Cave 4 — among the latest-dated DSS manuscripts. Alongside 4QDanᵃ and ᶜ it shows Daniel circulating in multiple simultaneous copies at the end of the Qumran period.',
    category: 'biblical',
    tier: 1,
  },
  {
    id: '4QDanᶜ',
    altId: '4Q114',
    commonName: 'Daniel c',
    book: 'Daniel',
    date: 'c. 50–1 BCE',
    source: 'DJD XVI (Ulrich et al., 2000)',
    description: 'Third Cave 4 Daniel witness; together the three manuscripts demonstrate substantial textual stability across different Qumran periods.',
    category: 'biblical',
    tier: 1,
  },
  {
    id: '11QPsᵃ',
    altId: '11Q5',
    commonName: 'Great Psalms Scroll',
    book: 'Psalms',
    date: 'c. 30–50 CE',
    source: 'DJD IV (Sanders, 1965)',
    description: 'Major Psalms witness with a different ordering of psalms and seven additional compositions not found in the Masoretic Psalter. Crucial for demonstrating that "Psalms" had a fluid textual and liturgical shape in the Second Temple period and was not yet a closed canonical collection.',
    category: 'biblical',
    tier: 1,
  },
  {
    id: '4QPsᶠ',
    altId: '4Q88',
    commonName: 'Psalms f',
    book: 'Psalms',
    date: 'c. 50–1 BCE',
    source: 'DJD XVI (Ulrich et al., 2000)',
    description: 'Commonly cited Cave 4 Psalms witness. Includes Psalm 22 and other texts; must be handled carefully because fragment placement and reconstruction are disputed in scholarship.',
    category: 'biblical',
    tier: 1,
  },
  {
    id: '4QXIIᵃ',
    altId: '4Q76',
    commonName: 'Twelve Prophets a',
    book: 'Minor Prophets',
    date: 'c. 150–100 BCE',
    source: 'DJD XV (Ulrich et al., 1997)',
    description: 'Oldest of the Cave 4 Minor Prophets fragments (4QXIIᵃ–g). The Twelve Prophets are collectively well-attested at Qumran and provide important comparative data for the Greek Minor Prophets tradition.',
    category: 'biblical',
    tier: 1,
  },
  {
    id: '8ḤevXIIgr',
    commonName: 'Greek Minor Prophets Scroll',
    book: 'Twelve Prophets (Greek)',
    date: 'c. 50 BCE–50 CE',
    source: 'DJD VIII (Tov, Kraft & Parsons, 1990)',
    description: 'From Naḥal Ḥever (not Qumran proper), but standardly grouped with the Judaean Desert scrolls. A Greek revision of the Septuagint Minor Prophets bringing the Greek text closer to a proto-Masoretic Hebrew Vorlage — central to the history of the Greek Bible.',
    category: 'biblical',
    tier: 1,
  },

  // ── TIER 1 · COMMENTARY ────────────────────────────────────────────────────

  {
    id: '1QpHab',
    commonName: 'Habakkuk Pesher',
    book: 'Habakkuk + commentary',
    date: 'c. 50–25 BCE',
    source: 'DJD I (Barthélemy & Milik, 1955)',
    description: 'Not a straight biblical manuscript, but vital for understanding how the Qumran community read and applied Scripture. The pesher (running commentary) on Habakkuk embeds the biblical text and interprets it eschatologically — a window into Second Temple scriptural exegesis.',
    category: 'commentary',
    tier: 1,
  },
  {
    id: '4QTest',
    altId: '4Q175',
    commonName: 'Testimonia',
    book: 'Deut · Num · Josh (proof-text collection)',
    date: 'c. 100–75 BCE',
    source: 'DJD V (Allegro, 1968)',
    description: 'A curated collection of messianic proof-texts from Deuteronomy, Numbers, and Joshua — not a biblical manuscript, but shows how Scripture was selected and arranged for theological argument in the Second Temple period.',
    category: 'commentary',
    tier: 1,
  },

  // ── TIER 2 · PARABIBLICAL (add later) ─────────────────────────────────────

  {
    id: '1Q20',
    commonName: 'Genesis Apocryphon',
    book: 'Genesis (Aramaic retelling)',
    date: 'c. 37 BCE–68 CE',
    source: 'DJD I (Barthélemy & Milik, 1955)',
    description: 'Not biblical text but an Aramaic retelling and expansion of Genesis narratives. Important for Second Temple Genesis interpretation and the history of biblical paraphrase.',
    category: 'parabiblical',
    tier: 2,
  },
  {
    id: '11Q19',
    commonName: 'Temple Scroll',
    book: 'Torah-related legal rewrite',
    date: 'c. 100–50 BCE',
    source: 'DJD XXIII (García Martínez, Tigchelaar & van der Woude, 1998)',
    description: 'The longest DSS scroll — a rewritten Torah presented as direct divine speech. Not a biblical manuscript but crucial for Torah legal interpretation and the question of Qumran\'s authoritative texts.',
    category: 'parabiblical',
    tier: 2,
  },
  {
    id: '1QS',
    commonName: 'Community Rule',
    book: 'Sectarian rule text',
    date: 'c. 100–75 BCE',
    source: 'DJD I (Barthélemy & Milik, 1955)',
    description: 'Primary organisational text of the Qumran community. Not a biblical manuscript; important for contextualising the community that preserved the biblical scrolls.',
    category: 'parabiblical',
    tier: 2,
  },
  {
    id: '1QM',
    commonName: 'War Scroll',
    book: 'Sectarian/apocalyptic',
    date: 'c. 50–25 BCE',
    source: 'DJD I (Barthélemy & Milik, 1955)',
    description: 'Apocalyptic text describing an eschatological war. Not a biblical manuscript; important historical context for the community\'s world-view and use of prophetic Scripture.',
    category: 'parabiblical',
    tier: 2,
  },
  {
    id: '3Q15',
    commonName: 'Copper Scroll',
    book: 'Treasure inventory',
    date: 'c. 25–68 CE',
    source: 'DJD III (Baillet, Milik & de Vaux, 1962)',
    description: 'Unique among the DSS — a copper document listing buried treasures. Not a biblical or theological text; important as a cultural artefact of the Qumran community.',
    category: 'parabiblical',
    tier: 2,
  },
];

export const CATEGORY_LABELS: Record<DSSCategory, string> = {
  biblical:      'Biblical Witnesses',
  commentary:    'Scriptural Commentary',
  parabiblical:  'Rewritten Bible & Parabiblical',
};

export const CATEGORY_DESCRIPTIONS: Record<DSSCategory, string> = {
  biblical:     'Manuscripts that directly transmit the Hebrew (or Greek) biblical text — used for source-text alignment and textual variant comparison.',
  commentary:   'Manuscripts that quote and interpret Scripture — valuable for understanding how the biblical text was read and applied in the Second Temple period.',
  parabiblical: 'Texts that retell, expand, or supplement biblical narratives — important context but not direct biblical witnesses.',
};
